// <auto-generated />
using System;
using HolidayTrackerApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HolidayTrackerApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129232105_FinalIdentitySetup")]
    partial class FinalIdentitySetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("HolidayTrackerApp.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnualLeaveQuota")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LeavePolicyId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNo")
                        .IsUnique();

                    b.HasIndex("LeavePolicyId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.Entities.WeekendDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WeekendPolicyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeekendPolicyId", "Day")
                        .IsUnique();

                    b.ToTable("WeekendDays", (string)null);
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HalfDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWorkdayOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Date")
                        .IsUnique();

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.LeaveBalance", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaidLeaveDebt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaidLeaveEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaidLeaveUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId", "Year");

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.LeavePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowNegativeBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnualLeaveDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarryOverCap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CarryOverToNextYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxNegativeDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinServiceDaysForPaidLeave")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LeavePolicies");
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.WeekendPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeekendPolicies");
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.Employee", b =>
                {
                    b.HasOne("HolidayTrackerApp.Domain.LeavePolicy", "LeavePolicy")
                        .WithMany()
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeavePolicy");
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.Entities.WeekendDay", b =>
                {
                    b.HasOne("HolidayTrackerApp.Domain.WeekendPolicy", "WeekendPolicy")
                        .WithMany("WeekendDays")
                        .HasForeignKey("WeekendPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeekendPolicy");
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.LeaveRequest", b =>
                {
                    b.HasOne("HolidayTrackerApp.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HolidayTrackerApp.Domain.WeekendPolicy", b =>
                {
                    b.Navigation("WeekendDays");
                });
#pragma warning restore 612, 618
        }
    }
}
